"use client";

import { useEffect, useState } from "react";
import { Sparkles, Shield } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

interface Props {
  mode: "checkin" | "journal" | "post_breathing";
  level?: number;
  text?: string;
  mood?: string;
  /** When this changes, the panel re-fetches a reflection. */
  trigger: number;
}

export function AIReflectionPanel({ mode, level, text, mood, trigger }: Props) {
  const [state, setState] = useState<{
    reflection: string;
    loading: boolean;
    source: "ai" | "fallback" | "safety" | null;
  }>({ reflection: "", loading: false, source: null });

  // Synchronizing with an external system (the /api/mind/reflect endpoint)
  // — exactly the use case effects are designed for. State updates happen
  // asynchronously (after fetch resolves), not synchronously in the body.
  useEffect(() => {
    if (trigger === 0) return;
    let cancelled = false;

    const run = async () => {
      // Microtask defer keeps the loading flag out of the synchronous body.
      await Promise.resolve();
      if (cancelled) return;
      setState((s) => ({ ...s, loading: true, reflection: "", source: null }));
      try {
        const res = await fetch("/api/mind/reflect", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ mode, level, text, mood }),
        });
        const data = await res.json();
        if (cancelled) return;
        setState({
          reflection: data.reflection ?? "",
          source: data.source ?? "fallback",
          loading: false,
        });
      } catch {
        if (cancelled) return;
        setState({
          reflection:
            "Thanks for taking a moment. Try one slow breath and notice one thing in the room around you.",
          source: "fallback",
          loading: false,
        });
      }
    };
    void run();

    return () => {
      cancelled = true;
    };
  }, [trigger, mode, level, text, mood]);

  const { reflection, loading, source } = state;

  return (
    <div className="mind-card-elev rounded-2xl p-6">
      <div className="mb-4 flex items-center gap-2">
        <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#6FFFE9]/10 border border-[#6FFFE9]/20">
          <Sparkles className="h-4 w-4 text-[#6FFFE9]" strokeWidth={1.75} />
        </div>
        <div className="flex-1">
          <h3 className="text-sm font-semibold mind-text-primary">Reflection</h3>
          <p className="text-[11px] mind-text-secondary">
            A gentle prompt — not advice, not therapy.
          </p>
        </div>
        {source === "safety" && (
          <span className="inline-flex items-center gap-1 rounded-full bg-rose-500/10 border border-rose-400/30 px-2.5 py-1 text-[10px] font-medium text-rose-300">
            <Shield className="h-3 w-3" /> Safety
          </span>
        )}
      </div>

      <div className="min-h-[88px]">
        <AnimatePresence mode="wait">
          {loading ? (
            <motion.div
              key="load"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="space-y-2"
            >
              <div className="skeleton h-3 w-11/12 rounded" />
              <div className="skeleton h-3 w-9/12 rounded" />
              <div className="skeleton h-3 w-7/12 rounded" />
            </motion.div>
          ) : (
            <motion.p
              key={reflection}
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.4 }}
              className="text-[15px] leading-relaxed mind-text-primary"
            >
              {reflection}
            </motion.p>
          )}
        </AnimatePresence>
      </div>

      <p className="mt-4 text-[10px] uppercase tracking-[0.2em] mind-text-secondary">
        {source === "ai" ? "Generated by AI" : source === "safety" ? "Crisis support" : "Default reflection"}
      </p>
    </div>
  );
}
